### ISSUE TITLE
MariaDB blocks the Codimd instance from connecting

### ISSUE THREAD

**Issue by caffeineflo** [linuxserver/docker-codimd#10]
The MariaDB instance won't allow the codimd instance to connect. 

```
codimd     | Sequelize CLI [Node: 10.17.0, CLI: 5.5.0, ORM: 5.8.12]
codimd     | 
codimd     | Loaded configuration file "../../config/config.json".
codimd     | Warning: got packets out of order. Expected 0 but received 1
codimd     | 
codimd     | ERROR: Host 'codimd.codimd_default' is not allowed to connect to this MariaDB server
```

**Comment by aptalca** [comment]
Fix your mysql database permissions

**Comment by CHBMB** [comment]
And please include all the requested info in our template, I'm closing this for now, as I don't think it's a bug report.  Feel free to open a new issue with the required information if the issue persists after trying the above.  

If we don't have the info to reproduce our end, we can't investigate.

**Comment by caffeineflo** [comment]
I used the exact `docker-compose.yml` that is on the README.md on this repo. Hence I didn't add more info since this was "out of the box" behavior that I thought you might wanted to fix for others that'll just grab the `docker-compose.yml` and run into this

**Comment by CHBMB** [comment]
@caffeineflo The `docker-compose.yml` isn't a copy and paste thing.  You need to substitute your own details.

**Comment by caffeineflo** [comment]
FYI my issue was related to #11 where the DB_HOST parameter was off. Easy mistake
