### ISSUE TITLE
Running /opt/codimd/bin/manage_users does not work

### ISSUE THREAD

**Issue by apiening** [linuxserver/docker-codimd#15]
I'm using the `docker-compose.yml` from the `readme.md`.
The docs for `codimd` describes that users can be created with the command `bin/manage_users` (see https://github.com/codimd/server/blob/master/docs/configuration-env-vars.md#email-local-account). 

I entered the `codimd container` with `docker-compose exec codimd bash` and used the following command to register a new user: `/opt/codimd/bin/manage_users --add my.email@address.com`.

Then I get the following errror:
```
(node:355) UnhandledPromiseRejectionWarning: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
    at connection.connect.err (/opt/codimd/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:170:24)
    at Connection.connectingErrorHandler (/opt/codimd/node_modules/pg/lib/client.js:194:14)
    at Connection.emit (events.js:198:13)
    at Socket.reportStreamError (/opt/codimd/node_modules/pg/lib/connection.js:73:10)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:355) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:355) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Any idea why this is?

**Comment by spasche** [comment]
You may have to set the `CMD_DB_URL` environment variable before running the binary.
With docker-compose, you can use the `run` command which injects environment variables:
```
docker-compose run --rm --entrypoint bash codimd
# copied from /etc/services.d/codimd/run
export CMD_DB_URL="mysql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
/opt/codimd/bin/manage_users --add my.email@address.com
```

**Comment by mabayhan** [comment]
I tried to add CMD_DB_URL to docker-compose.yml but it did not work. 
I tried both of these,

- CMD_DB_URL="mysql://user_name:PassW0rd@db.host:3306/codi"
- CMD_DB_URL="mysql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

For now, only way looks like @spasche's method.

**Comment by apiening** [comment]
Thank you @spasche your solution worked for me.
In addition, I had to add the variables **CMD_DOMAIN** and **CMD_PROTOCOL_USESSL** to get the login to work.
