### ISSUE TITLE
No Plantuml support

### ISSUE THREAD

**Issue by kepochan** [linuxserver/docker-codimd#16]
Plantuml is not supported.

Pulled latest on 30/11/20.
Digest: sha256:056ef5ba7bb4e6c86e9e3bf17729a3fc28d30ad3493b152125ee010256e53715

![image](https://user-images.githubusercontent.com/26228238/97762364-90535200-1b08-11eb-81e1-1713c2b159ca.png)

**Comment by kosssi** [comment]
@kepochan LinuxServer is not the owner of this product, you should put your issue on the following repository https://github.com/hedgedoc/hedgedoc and close this ;)

Yes CodiMD was renamed to HedgeDoc.
