### ISSUE TITLE
Minor issues in README

### ISSUE THREAD

**Issue by SISheogorath** [linuxserver/docker-codimd#4]
I just checked the README and hat to notice that you build your images from the [Community project](https://github.com/codimd/server) while pointing to the HackMD team based-version of the docs for it, (hosted on hackmd.io).

This will cause problems over time as those two projects are going to move apart from each other.

Also you list the instance from CERN as example, but I would recommend to go for the official demo instance instead: https://demo.codimd.org

Just as a hint, we would be happy to add an additional way to install CodiMD using Linux-Server.io to [our install docs](https://github.com/codimd/server/tree/master/docs/setup), if you want to provide a short short description of the project and a link to your instruction docs.

**Comment by CHBMB** [comment]
@SISheogorath Awesome, thanks for pointing this out, I'll sort it out.

**Comment by SISheogorath** [comment]
I also saw you have two readme(-)vars file, so was a bit confusing, otherwise I would have fixed it myself ^^

**Comment by CHBMB** [comment]
@SISheogorath The `README.md` is automatically generated from `readme-vars.yml`  Don't worry, I can fix it and generate a new `README.md` :+1:

**Comment by thelamer** [comment]
@CHBMB made the requested changes. Just a heads up though github wiki gets way better SEO than their code pages which are basically non existent. 
If I was you I would leverage the wiki section which has a proper robots.txt, or an external service like readthedocs or gitbook. 
https://github.com/codimd/server/wiki

**Comment by SISheogorath** [comment]
I'm already looking into getting a dedicated docs page for CodiMD :) But we have quite limited resources right now and really try to avoid the wiki as it gets outdated quite fast
