### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by kroschu** [linuxserver/docker-codimd#6]
When i try to type cyrillic letters i receive this error.

**Comment by kroschu** [comment]
More details:
https://demo.codimd.org/s/H1tB_rqWS

**Comment by thelamer** [comment]
This is the backend database setting not the frontend application. 
You can get around this by setting the following settings in:
```
/config/custom.cnf
```
In our MariaDB container before creating your databases: 
```
[mysqld]
collation-server = utf8_unicode_ci
init-connect='SET NAMES utf8'
character-set-server = utf8

[mysql]
default-character-set=utf8
```

These need to be appended to existing blocks (mysql and mysqld) you are not just adding these copy and paste. 

After that go in and create the database and user via the mariadb command line: 
```
create database codimd;
CREATE USER 'codimd'@'%' IDENTIFIED BY 'yourpassword';
GRANT ALL PRIVILEGES ON codimd.* TO 'codimd'@'%';
FLUSH PRIVILEGES;
```

![Screenshot_2019-07-15_12-52-02](https://user-images.githubusercontent.com/1852688/61245077-8d103900-a700-11e9-8c6e-8e51eb5ef73e.png)

After this it works fine for me. 

You should also report this issue upstream to the project : 
https://github.com/hackmdio/codimd/issues

You should not be setting encoding server wide, they can set encoding and sort to utf8 all the way down to a column level with their database migration scripts here: https://github.com/hackmdio/codimd/tree/develop/lib/migrations

The specific db and column this error occurs on is : 

database.Notes.content  << they will know that this means
